import { Router } from "express";
import { AdminController } from "../controllers/AdminController";
import { AdminPageApiController } from "../controllers/AdminPageApiController";
import { AdminFileApiController } from "../controllers/AdminFileApiController";
import { AdminUserApiController } from "../controllers/AdminUserApiController";
import { AdminMenuApiController } from "../controllers/AdminMenuApiController";
import { AdminCommentApiController } from "../controllers/AdminCommentApiController";
import { AdminSettingApiController } from "../controllers/AdminSettingApiController";
import { AdminCodeblockApiController } from "../controllers/AdminCodeblockApiController";
import { AdminThemeApiController } from "../controllers/AdminThemeApiController";

const router = Router();

router.get('/', AdminController.index);
router.get('/login', AdminController.login);
router.post('/login', AdminController.login);
router.get('/logout', AdminController.logout);
router.get('/users', AdminController.users);
router.get('/pages', AdminController.pages);
router.get('/files', AdminController.files);
router.get('/menus', AdminController.menus);
router.get('/comments', AdminController.comments);
router.get('/codeblocks', AdminController.codeblocks);
router.get('/settings', AdminController.settings);
router.get('/themes', AdminController.themes);
router.get('/new-page', AdminController.newPage);
router.get('/edit-page/:id', AdminController.editPage);
router.post('/api/page', AdminPageApiController.post);
router.put('/api/page/:id', AdminPageApiController.put);
router.delete('/api/page/:id', AdminPageApiController.delete);
router.put('/api/page/:id/change-status', AdminPageApiController.changeStatus);
router.put('/api/page/:id/set-as-homepage', AdminPageApiController.setAsHomepage);
router.get('/api/page/:id/comments', AdminPageApiController.getComments);
router.get('/api/pages', AdminPageApiController.getAll);
router.get('/api/file', AdminFileApiController.getAll);
router.post('/api/file', AdminFileApiController.post);
router.delete('/api/file/:id', AdminFileApiController.delete);
router.put('/api/file/:id', AdminFileApiController.put);
router.post('/api/user', AdminUserApiController.post);
router.put('/api/user/:id', AdminUserApiController.put);
router.delete('/api/user/:id', AdminUserApiController.delete);
router.get('/api/users', AdminUserApiController.getAll);
router.post('/api/menu', AdminMenuApiController.post);
router.put('/api/menu/:id', AdminMenuApiController.put);
router.put('/api/menu/:id/items', AdminMenuApiController.putItems);
router.put('/api/menu/:id/set-as-default', AdminMenuApiController.setAsDefault);
router.delete('/api/menu/:id', AdminMenuApiController.delete);
router.get('/api/menus', AdminMenuApiController.getAll);
router.post('/api/comment', AdminCommentApiController.post);
router.put('/api/comment/:id', AdminCommentApiController.put);
router.delete('/api/comment/:id', AdminCommentApiController.delete);
router.get('/api/comments', AdminCommentApiController.getAll);
router.post('/api/setting', AdminSettingApiController.post);
router.put('/api/setting/:id', AdminSettingApiController.put);
router.delete('/api/setting/:id', AdminSettingApiController.delete);
router.get('/api/settings', AdminSettingApiController.getAll);
router.put('/api/settings', AdminSettingApiController.updateAll);
router.post('/api/codeblock', AdminCodeblockApiController.post);
router.put('/api/codeblock/:id', AdminCodeblockApiController.put);
router.delete('/api/codeblock/:id', AdminCodeblockApiController.delete);
router.get('/api/codeblocks', AdminCodeblockApiController.getAll);
router.get('/api/themes', AdminThemeApiController.getAll);
router.put('/api/theme/:id', AdminThemeApiController.put);
export default router;